.circleci/config.yml, jest.config.js, src/blocks/Card.stories.tsx, src/blocks/ImageCard.stories.tsx, src/blocks/ImageCard.tsx, src/forms/MultiSelectField.tsx, src/headers/HeadingGroup.tsx, src/page_components/listing/ListingCard.stories.tsx, src/tables/AgTable.stories.tsx, src/tables/AgTable.tsx, src/tables/StandardTable.tsx
In porting over, we missed running the accessibility suite in CircleCi.
To test this PR, ensure the tests run and pass. In getting the suite to work, I realized some suites were silently failing due to a config issue, and once they were running some tests were failing, so it involves a few a11y fixes as well. One of the errors I had to explicitly ignore due to it being a third party issue with ag-table.
=> test: run a11y suite in circleci

.eslintrc.js, .npmignore, commitlint.config.js, package.json, src/notifications/ErrorMessage.tsx, yarn.lock
Two linting scripts now run on commit: eslint, and conventional commit formatting
To test this, in a component file locally, add a variable you don't use and try to commit with a valid cc format. Linting should run and the commit should fail.
Then try to commit in a not-conventional-commit format (i.e. just `test`) and that should fail.
=> chore: add linting on commit

package.json
#issue n/a
By default, `start-storybook` and `yarn start` by extension chooses a random port to run on. However, for folks developing on remote machines, that breaks port forwarding since we have to specify specific ports to forward.
I changed the default functionality of `yarn start` to choose port 40791 (nothing specific about this port except that it was the port chosen by my first run of yarn start) -- I figure that this is a detail that most people not SSHing into remote machines will even notice, but if there is an issue here I'm happy to alternatively implement it such that so that you can pass in a argument of a port or even add a new command like `yarn start-consistent-port`.
Checkout onto `main`, then `yarn start`. Observe that the local Storybook is brought up on a random port. …
=> chore: Update yarn start build local Storybook on a consistent port

src/page_components/listing/listing_sidebar/Contact.tsx, src/text/Description.scss, src/text/Description.tsx
There are two issues within DAHLIA related to translations. The first is that, within the Contact component, we need to have the ability to pass a classname to the Contact Title element. This allows us to specifically target that element for machine translation.
The second issue related to the Description component. Currently, the widths of the term and definition column are hardcoded as 33% and 66%, respectively. However, there are instances (specifically at small screen widths) when a single word exceeds the width of the term column. For example, in English Appliances fits into the term column, but when translated to Spanish, this term becomes "Electrodomésticos" which would run over into the definition column. A fix for this is to use grid to allow the columns width to be flexible but …
=> fix: add variable width to description titles

.releaserc.json
At the moment, we're not releasing this package on every commit even if the commit message is in the conventional commit format.
For example, you can see that the [SiteHeader refactor PR](https://github.com/bloom-housing/ui-components/pull/21) was committed to main with this message (`refactor: update SiteHeader to support CSS overrides`) but was not actually released. If you check out [the GitHub action](https://github.com/bloom-housing/ui-components/actions/runs/4224903177/jobs/7336462191) for the release of this PR you see this in the output: `[@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release`
There is a [default set of rules for release](https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js) which from the set of …
=> refactor: release all types of commit tags

src/blocks/ImageCard.scss, src/blocks/ImageCard.tsx
#29 
DAHLIA identified an issue where the listing tag renders on top of the slide out mobile menu. This occurred whenever the listing tag was present.
**In storybook**
Check to ensure that the listing tags are rendering correctly.
**In DAHLIA (or Bloom)**
1. Check to ensure that the listing tags render correctly on the listing details page and the rental listings page.
2. Using the inspector or an emulator, change the viewport to be a mobile version. 
3. Go to the listings page and find a listing with listing tags on them. 
4. Open the slide out menu by clicking the hamburger icon in the top right
5. The Listing tag should be underneath the menu
6. Try this on the listing details page
Describe the tests that you ran to verify your changes. Please also list any relevant details for your …
=> fix: Remove Z-Index Requirement for Listing Tags

src/global/tables.scss, src/tables/StackedTable.stories.tsx, src/tables/StackedTable.tsx
DAHLIA wants to display multiple values in a cell (see screenshot). This PR adds support for an array to be passed into the StackedTable component.
- open storybook, ensure no visual regressions occurred in any of the StackedTable variants
- ensure code changes don't cause breaking changes
- ensure the changes add support for the screenshot
- run and link bloom and verify that stackedTable instances look the same
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …
=> feat(stackedtable): add cell array support

src/headers/PageHeader.stories.tsx, src/headers/PageHeader.tsx
#39 
For the Get Assistance pages, we want to have an image in the background of the header.
The best way to test this is on Storybook. There is now a variant where a background image is provided.
=> fix: Add optional background to page header

index.ts, src/blocks/ImageCard.scss, src/blocks/ImageCard.stories.tsx, src/blocks/ImageCard.tsx, src/blocks/Tooltip.scss, src/blocks/Tooltip.tsx, src/text/Tag.tsx
#55
Aligns the ImageCard component with the changes in Detroit.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/blocks-image-card--image) to the stories on [this PR](https://deploy-preview-42--storybook-bloom-dev.netlify.app/?path=/story/blocks-image-card--image). This PR includes pulling over the Tooltip component.
While testing in Detroit I noticed that while we used to show a tooltip on the `Verified` tags on the ImageCard we no longer were passing that in. Jesse considers that a regression so once we uptake in Detroit we will re-pass in that tooltip.
- Either review the Storybook preview or pull the changes down …
=> fix: align ImageCard with detroit updates

src/blocks/ViewItem.scss, src/blocks/ViewItem.tsx
#58
Allows for custom styling. There is an additional prop in Detroit for a label class name but the style overrides solve this problem.
This component is relatively soon --> seeds.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/blocks-view-item--default) to stories on [this PR](https://deploy-preview-45--storybook-bloom-dev.netlify.app/?path=/story/blocks-view-item--default).
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …
=> fix: align ViewItem with detroit updates

src/actions/ExpandableContent.stories.tsx, src/actions/ExpandableContent.tsx
#60
Allows for the content to be rendered above or below the expand button.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/actions-expandable-content--standard) to stories on [this PR](https://deploy-preview-47--storybook-bloom-dev.netlify.app/?path=/story/actions-expandable-content--standard).
=> fix: align ExpandableContent with detroit updates

package.json
Currently getting this error in core on the latest version: `Cannot find module 'tailwindcss-rtl'`
That was added as a dev dependency but it needs to be an explicit dependency, but also I'm not sure if this will fix the issue because linking locally from main works on core - it must not 100% reflect what it's like to pull in an external dependency
=> fix: add explicit dependency

src/forms/Field.tsx
[#3283](https://github.com/bloom-housing/bloom/issues/3283)
Allows for one new optional class name prop.
N/A
=> fix: align Field with detroit updates

src/headers/HeadingGroup.tsx
#61
Includes an update to the a11y label on the HeadingGroup from Detroit.
The change here is neither exactly what was was in UIC or is in Detroit - it removes the roles/descriptions from the p tag.
A journey: 
Previous method: `<p role="doc-subtitle">`
Detroit method: `<p aria-roledescription="subtitle">`
[Link that says previous method is questionable
](https://adrianroselli.com/2020/08/be-wary-of-doc-subtitle.html) and another great [sub-link from that page](https://www.tpgi.com/subheadings-subtitles-alternative-titles-and-taglines-in-html/), takeaways:
`Do not use h1-h6 to mark up Subheadings, subtitles, alternative titles and taglines in <hgroup>, use <p> elements.`
`Apply additional semantic information via ARIA with an abundance of caution as it may well end up being unwanted noise …
=> fix: align HeadingGroup with detroit updates

src/headers/StepHeader.scss, src/headers/StepHeader.tsx
#64
This component is only used in Detroit, but looks like at some point we pulled it back to core, and then made improvements in Detroit.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/headers-step-header--basic-dynamic) to stories on [this PR](https://deploy-preview-51--storybook-bloom-dev.netlify.app/?path=/story/headers-hero--with-listings).
On …
=> fix: align StepHeader with detroit updates

src/navigation/LanguageNav.scss, src/navigation/LanguageNav.stories.tsx
#69
Adds V2 styling for the component.
Compare the story on [dev](https://storybook.bloom.exygy.dev/?path=/story/navigation-languagenav--default) to the story on [this PR](https://deploy-preview-68--storybook-bloom-dev.netlify.app/?path=/story/navigation-languagenav--default).
You can also see it in some of the SiteHeader stories ([dev](https://storybook.bloom.exygy.dev/?path=/story/headers-site-header--with-language-and-mobile-notice) [PR](https://deploy-preview-68--storybook-bloom-dev.netlify.app/?path=/story/headers-site-header--with-language-and-mobile-notice)).
- Either review the Storybook preview or pull the changes down locally and …
=> fix: align LanguageNav with Detroit updates

src/page_components/listing/ListingCard.scss, src/page_components/listing/ListingCard.stories.tsx, src/page_components/listing/ListingCard.tsx
#87
Adds a few new CSS overrides, allows for a custom header priority, and changes the sub-subheader into a p tag for better a11y.
QA Notes:
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/page-components-listing-card--with-standard-table) and on [this PR](https://deploy-preview-79--storybook-bloom-dev.netlify.app/?path=/story/page-components-listing-card--with-standard-table).
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the …
=> fix: align ListingCard with detroit updates

src/global/text.scss, src/sections/GridSection.scss, src/sections/GridSection.stories.tsx, src/sections/GridSection.tsx
#83
A few new CSS variables, and an optional edit button.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/sections-grid-section--default-three-columns) and on [this PR](https://deploy-preview-82--storybook-bloom-dev.netlify.app/?path=/story/sections-grid-section--default-three-columns).
The edit story will look different, bc now there is actually an edit button :)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is …
=> fix: align GridSection with detroit updates

src/global/app-css.scss, src/page_components/listing/ContentAccordion.scss, src/page_components/listing/ListingDetailHeader.scss, src/page_components/listing/ListingDetailHeader.stories.tsx, src/page_components/listing/ListingDetailHeader.tsx, src/page_components/listing/ListingDetails.scss, src/page_components/listing/ListingDetails.tsx
#81
Updates to V2 styling and pulls over a few RTL fixes. There will be a darker text color on the subtitle to meet AAA WCAG color constrast.
There is a new [story](https://deploy-preview-80--storybook-bloom-dev.netlify.app/?path=/story/listing-listingdetailheader-%F0%9F%9A%A9--default) added you can compare to a [prod listing](https://housing.acgov.org/listing/19c24c16-3ecc-4a0e-996e-76b507cd6d71/alexan_webster_2330_webster_street_oakland_ca).
- Either explicitly ask a clarifying question, request changes, or approve the PR if …
=> fix: align ListingDetailHeader with detroit updates

src/tables/StandardTable.tsx
This issue came up when trying to pull in the latest ui-component changes to core. There is a typing error on StandardTable that is exposed when upgrading @types/react to 18. I will continue to investigate on why this isn't caught in ui-component build step, but this should unblock people from pulling it into bloom.
=> fix: correct typing on standardtable

src/blocks/FormCard.scss, src/blocks/ImageCard.scss, src/blocks/InfoCard.scss, src/blocks/InfoCard.tsx, src/global/blocks.scss, src/global/forms.scss, src/global/mixins.scss, src/headers/PageHeader.scss, src/page_components/listing/AdditionalFees.tsx, src/tables/GroupedTable.tsx, src/tables/StandardTable.tsx
This PR includes a handful of new CSS variables that we need to customize UIC that were missed in the first round.
There is also one bug fix around page header mobile alignment, a fix around rendering an empty section in additional fees, and the ability to add an icon in a table header (Detroit's AMI icon).
=> fix: more alignment for detroit components

src/navigation/FooterNav.scss
#93  
It removes full width on large screen from footer copyright (couldn't find any scenario when we need it). Previously footer copyright pushed out rest to right side.
Go to footer, on large screen it should display all in one horizontal line (if there is enough space) 
=> fix: Footer links are stacked on top of each other

src/blocks/ImageCard.scss
There is a bug in the Image Card when pulling the latest changes into core. there was a new CSS variable called --leader-width added to the ImageCard.scss. The issue we run into is the .image-card--leader is higher in the DOM than the place where the --leader-width variable is getting set (.image-card)
This fixes the issue by moving the `--leader-width` variable to the `.image-card--leader` class.
Long term I don't think the `image-card--leader` should be in ui-components at all as its usage is only used in bloom and not really part of the imageCard
Issue example 1
Issue example 2
This can only be tested by linking the change in bloom and going to listings detail page.
- Review the code itself …
=> fix: move leader-width for image card

src/helpers/preferences.tsx
We are still getting [application submission errors](https://exygy.slack.com/archives/C02G1S19QA2/p1685474689348509) with this message: `preferences.0.options.0.extraData.0.value.street must be shorter than or equal to 64 characters`.
We've made two fixes for this [in core recently](https://github.com/bloom-housing/bloom/pull/3413), but I think we missed this set of fields because they're over here. The backend has a 64 character validation on these fields and this is adding that validation to the frontend as well.
=> fix: add frontend validation to preference address form fields

src/tables/AgTable.tsx
[#3556](https://github.com/bloom-housing/bloom/issues/3556)
Previously first sort on new session was only frontend side. This PR removes code that blocked first sort request (so first in session click on sortable column header) and adds initial sort functionality that picks first `sort` field from `columns` array.
This is part of [#3556](https://github.com/bloom-housing/bloom/pull/3576) so should be tested also with those changes, but it should work without them.
On partners site go to listing applications tab `/listings/[id]/applications`. By default `application submitted date` should be properly sorted. Other sortable fields should trigger backend sort on first click (table will twitch, and request will be made).
Same for `listings`, but status will be default sort (on `3556/...`  core …
=> fix: trigger backend sorting on initial table load

src/forms/Textarea.tsx
#119 
Allows for the Textarea to receive validation.
Difficult to test outside of the context of an existing form which isn't something we have set up in stories. I have this linked locally with a new set of changes to listings approval that shows the validation comes through which I'm happy to demo if needed.
=> fix: allow textarea validation

src/notifications/ApplicationStatus.tsx
[#3630](https://github.com/bloom-housing/bloom/issues/3630)
In `/listing/:id` For application status (blue block in top right) when there is nothing to display it will display nothing instead of empty component.
For hidden application status go to partners listing and set it to `application process` -> `How is the application review order determined?` -> `lottery`.
And empty `Application Due Date` (the one that is all the way down in application process tab). For rest variants it probably should be visible, but worth to check if i missed something.
- Either review the Storybook preview or pull the changes down locally and test that the …
=> fix: hide application status when no content to display

src/tables/StandardTable.tsx
[#44](https://github.com/bloom-housing/Bloom-Doorway/issues/44)
Adds className prop to StandardTable component to be able to use it in doorway.
[In this PR](https://github.com/metrotranscom/doorway/pull/367) we have that class utilised, so can be tested on that PR.
=> fix: add className prop to StandardTable

src/overlays/Modal.docs.mdx, src/overlays/Modal.scss, src/overlays/Modal.stories.tsx, src/overlays/Overlay.scss
#133 
This PR updates the modal and overlay components so that the actions in the footer will be visible on mobile devices whether the bottom search bar is up or not. This fix is made possible by using dvh which is supported by over 90% of users ([source](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic)).
In the event that dvh is not supported, this PR includes a fallback solution which adds static padding which will keep full height modals actionable.
Setting the max height to 100dvh or dynamic view height prevents the modal buttons being blocked since it adjusts based on whether browser ux pieces are expanded or retracted (ie. search bar).
The fallback approach came to be since without dvh, we have to manually move the full-screen modal up to sit higher than …
=> fix: mobile modal button visible

src/overlays/LoadingOverlay.tsx
This PR is for Issue #135. 
This removes the alert role from LoadingOverlay, which was causing screen readers to jump to the start of the overlay when interacting with operable components. The alert role should only be used sparingly for text content: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role
See Issue #135.
=> fix: remove LoadingOverlay alert role

src/forms/Field.stories.tsx, src/forms/Field.tsx
#155 
This change allows for the Field error message to either be a string or a JSX.Element. This will allow consumers to pass things like hyperlinks in the error message
This change extends the type definition of an optional prop. I have included a story to illustrate this new feature.
=> fix: allow for jsx elements on field error message

src/forms/DateField.stories.tsx, src/forms/DateField.tsx
[Doorway #771](https://github.com/metrotranscom/doorway/issues/771)
This PR adds a change event handler to ensure only numbers can be typed into the date fields (requires the host page to pass along a `setValue` prop). It also improves some of the validation logic to be more robust.
[Storybook example](https://deploy-preview-157--storybook-bloom-dev.netlify.app/?path=/story/forms-date-field--default) (there's a test submit button as well to verify validation behavior)
- Either explicitly ask a clarifying question, request …
=> feat: allow only numbers when typing in the Date field

src/forms/DateField.tsx, src/forms/TimeField.stories.tsx, src/forms/TimeField.tsx
[Doorway #771](https://github.com/metrotranscom/doorway/issues/771)
This provides the same input masking for Time fields as Date fields (only numbers are allowed).
Storybook: https://deploy-preview-158--storybook-bloom-dev.netlify.app/?path=/story/forms-time-field--default
=> feat: add input masking for numbers only in TimeField

src/sections/ResponsiveContentList.tsx
#159 
This PR exposes the resetNextUuid function provided by React-Accessible-Accordion. This will allow consumers to stabilize the id's used in the Accordion logic. 
This makes no functionality changes to any components. 
=> fix: expose resetNextUuid

src/overlays/LoadingOverlay.tsx
#issue
https://github.com/bloom-housing/ui-components/issues/165#issue-2973361067
Replace deprecated ReactChild with ReactNode 
This causes an "Type 'Element' is not assignable to type 'string'" error with ReactChild, which is resolved by updating to ReactNode.
```
const Foo = () => {
return <div>foo</div>
}
<LoadingOverlay isLoading={loading}>
<Foo />
<Foo />
</LoadingOverlay>
```
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to …
=> fix: replace deprecated ReactChild with ReactNode

src/forms/Field.tsx
#167
This PR builds custom onBlur and onFocus support for the currency field type to support validation. Given that inputProps are passed in as unknown, I had to do some wacky typescript stuff to make things work. Open to feedback here but this is the simplest approach that functioned without errors.
This can be tested by adding the following line to the currency field story: 
`inputProps={{ onBlur: () => console.log("please") }}`
A note that console logging is sort of inconsistent in story book and you may need to open a close the console in between clicking in and out of the field to see your "please"
- Either review the Storybook preview or …
=> fix: custom blur + focus support

src/page_components/listing/listing_sidebar/QuantityRowSection.stories.tsx, src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
https://github.com/bloom-housing/bloom/issues/4858
A three digit waitlist size was wrapping onto multiple lines.
Check out the [new story](https://deploy-preview-170--storybook-bloom-dev.netlify.app/?path=/story/listing-sidebar-quantity-row-section--custom-description). This is not the most elegant fix, but didn't want to sink too much time into UIC.
=> fix: three digit waitlist size
