src/page_components/listing/AdditionalFees.tsx
Fix bloom-housing/bloom#3220 by removing some unnecessary margin classes (maybe cruft from a previous world where this component had application fee & deposit side by side?).
I haven't used GitHub properly in years, plz advise if I miss anything!
=> Fix alignment issue in AdditionalFees component

src/page_components/listing/ContentAccordion.stories.tsx, src/page_components/listing/ContentAccordion.tsx
DAHLIA has designs for an instance of the ContentAccordion component to be initially open. This PR adds a prop that allows the parent component to set that. After the component has been rendered expanded, it should then function the same as before (closing and opening functioning should be the same). 
- open storybook, ensure this causes no breaking changes (all the variants except the new look should look the same)
- ensure code changes to introduce breaking changes
- ensure changes allow the ContentAccordion to be initially open. 
- Review the code itself from a style …
=> feat(contentAccordion): add initialExpanded prop

src/lists/PreferencesList.tsx
#36 
This PR adds the option to add classes onto the Preference Description element. This will be used by DAHLIA to support machine translated text.
This is an optional change and should have minimal impact. The best way to test is to check out the code, and to bring this change into DAHLIA and view how `/listings/a0W4U00000IgqQVUAZ` has machine translated custom text as its second preference.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is …
=> fix: add class name option to description

.circleci/config.yml, src/tables/StackedTable.stories.tsx, src/tables/StackedTable.tsx
Fixes the [broken build](https://github.com/bloom-housing/ui-components/actions) from the last commit to main
You can test by running `yarn build` locally - I added a job to CircleCi to build so we can catch these at the PR level
I tested main's current code with the new job and you can see it ["successfully" fails](https://app.circleci.com/pipelines/github/bloom-housing/ui-components/118/workflows/88e5af0e-fd75-407c-9468-4cce533d1ca0/jobs/304) as expected
=> fix: fix type issues

src/global/tokens/sizes.scss, src/overlays/Modal.scss, src/overlays/Modal.stories.tsx, src/overlays/Modal.tsx
[#3312](https://github.com/bloom-housing/bloom/issues/3312)
Updates the modal content to incorporate the needs from Detroit
Ensure there are no regressions on desktop or mobile in our Modal stories
=> feature: align modal with detroit updates

src/blocks/InfoCard.scss, src/blocks/InfoCard.stories.tsx, src/blocks/InfoCard.tsx, src/page_components/listing/AdditionalFees.stories.tsx, src/sections/InfoCardGrid.scss, src/sections/InfoCardGrid.tsx
#54 
Makes updates to the InfoCard and InfoCardGrid components to support Detroit's needs.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/blocks-info-card--default) and on [this PR](https://deploy-preview-41--storybook-bloom-dev.netlify.app/?path=/story/sections-info-card-grid--three-cards). You will see slightly less right margin on the grid.
On …
=> fix: align InfoCard and InfoCardGrid with detroit updates

src/actions/Button.scss, src/actions/Button.tsx, src/icons/Icon.scss, src/icons/Icon.tsx
#59
Allows for a few more custom styles and a few optional props between Button and Icon.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/actions-button--standard) to stories on [this PR](https://deploy-preview-45--storybook-bloom-dev.netlify.app/?path=/story/actions-button--standard).
=> fix: align Button with detroit updates

__tests__/blocks/ActionBlock.test.tsx, package.json, src/blocks/ActionBlock.scss, src/blocks/ActionBlock.stories.tsx, src/blocks/ActionBlock.tsx, tailwind.config.js, yarn.lock
#57
Allows for a custom heading priority and for two new RTL styles that required adding in the package.
Commit message: `BREAKING CHANGE: changes the type of the header prop to align with the Heading component interface`
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/blocks-action-block--block-with-icon) to stories on [this PR](https://deploy-preview-44--storybook-bloom-dev.netlify.app/?path=/story/blocks-action-block--block-with-icon).
- Either explicitly ask a clarifying question, request changes, …
=> feat: align ActionBlock with detroit updates

src/headers/Hero.scss, src/headers/Hero.stories.tsx, src/headers/Hero.tsx
#62
Allows V2 styling and a custom content section.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/headers-hero--with-listings) to stories on [this PR](https://deploy-preview-51--storybook-bloom-dev.netlify.app/?path=/story/headers-hero-%F0%9F%9A%A9--with-listings).
=> fix: align Hero with detroit updates

src/headers/PageHeader.scss, src/headers/PageHeader.stories.tsx
#63
Allows V2 styling and pulls over some nice CSS fixes from Detroit.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/headers-page-header--with-text-content) to stories on [this PR](https://deploy-preview-53--storybook-bloom-dev.netlify.app/?path=/story/headers-page-header--with-text-content).
=> fix: align PageHeader with detroit updates

src/navigation/FooterNav.scss
#67
Adds one new class + one override variable.
There weren't any existing stories and it doesn't really make sense to add them considering the layout of these in context. When we go to seeds I think this won't end up being an individual component.
=> fix: align FooterNav with detroit updates

src/navigation/ProgressNav.tsx
#72
Adds one new optional prop.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/navigation-progress-nav-%F0%9F%9A%A9--default) and on [this PR](https://deploy-preview-70--storybook-bloom-dev.netlify.app/?path=/story/navigation-progress-nav-%F0%9F%9A%A9--default).
=> fix: align ProgressNav with detroit updates

src/notifications/AlertBox.scss, src/notifications/AlertBox.tsx
#73
Allows for a few more custom styles and adds a few explicit styles on the inverse version.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/notifications-alert-box--alert-box-alert) and on [this PR](https://deploy-preview-71--storybook-bloom-dev.netlify.app/?path=/story/notifications-alert-box--alert-box-alert).
=> fix: align AlertBox with detroit updates

src/global/tables.scss, src/global/text.scss, src/page_components/listing/ContentAccordion.tsx, src/tables/CategoryTable.stories.tsx, src/tables/CategoryTable.tsx
I didn't think this PR needed an issue for QA bc this component is only used in SF even though it still lives here.
This component is only used in SF right now. They have a few UX requests:
The styling within the header and between the sections is not internal to the component, so this handles the letter spacing, the border under the subheader, the margin after the last table, and some font size and margin discrepancies that weren't explicitly called out.
You can check out the [existing stories](https://deploy-preview-90--storybook-bloom-dev.netlify.app/?path=/story/tables-categorytable--basic).
Changes
* The last table has no bottom margin
* The letter spacing of the table headers is reset to normal
* There is no longer a border under the table headers
* The border under the category …
=> fix: update ux issues in category table

src/overlays/LoadingOverlay.scss
#77
Adds one new CSS variable.
Compare the stories on [dev](https://storybook.bloom.exygy.dev/?path=/story/overlays-loading-overlay--default) and on [this PR](https://deploy-preview-76--storybook-bloom-dev.netlify.app/?path=/story/overlays-loading-overlay--default).
=> fix: align LoadingOverlay with detroit updates

src/overlays/Overlay.scss
N/A
Adds one new CSS variable.
There are no stories and it's not a component where it makes sense to add them, hoping for just a code review.
=> fix: align Overlay with detroit updates

src/text/Description.scss, src/text/Description.stories.tsx, src/text/Description.tsx
#85
Updates the Description component with V2 styles. Also updates one style here to use what is in Detroit, which is to extend the left border the full height of the title.
(New style)
(Old style)
I added [two new stories](https://deploy-preview-84--storybook-bloom-dev.netlify.app/?path=/story/text-description-%F0%9F%9A%A9--default), you can also link locally to core, comparing to dev to ensure there are no regressions.
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining …
=> fix: align Description with detroit updates

__tests__/blocks/FormCard.test.tsx, src/blocks/FormCard.scss, src/blocks/FormCard.stories.tsx, src/blocks/FormCard.tsx, src/global/mixins.scss
#56
Aligns the FormCard component with the changes in Detroit. There are no existing stories but you can check out [two new ones](https://deploy-preview-43--storybook-bloom-dev.netlify.app/?path=/story/blocks-form-card--default-card). It's sort of funky that the no header state has no internal styling at all, but that's the existing behavior.
The `isVisible` prop wasn't used anywhere so I removed it since I already had to make a breaking change to that prop to accommodate a custom header priority.
Commit message indicates: `BREAKING CHANGE: removes the isVisible prop and re-types the heading prop`
There weren't any existing stories for this component. If you link you can compare the two versions (title/no title) by looking at an application section (title flavor) and at the forgot …
=> feat: align FormCard with detroit updates

package.json, src/forms/PhoneMask.tsx, src/navigation/LanguageNav.scss, src/page_components/listing/ListingDetailHeader.scss, yarn.lock
There is a [dependency issue](https://app.netlify.com/sites/partners-bloom-dev/deploys/6424787a19a3340008091bc3) in core uptaking ui-seeds. There was a missing dependency in this package `@types/react`, so this PR adds that dependency and fixes the related type error. It also fixes two CSS warnings.
=> feat: fixup react types

src/blocks/ImageCard.tsx, src/forms/Field.tsx, src/tables/GroupedTable.tsx, src/tables/StandardTable.tsx
#103
Aligns with some changes in Detroit that have gone in since the alignment work started.
Just adds some new optional a11y behavior.
=> fix: remaining detroit alignment

src/blocks/ImageCard.scss
#issue
#120 
In DAHLIA the Listing tag is appearing on top of the slide out menu. We [fixed this a bit ago by removing the Z-Index requirement](https://github.com/bloom-housing/ui-components/pull/30/files), but it looks like that was [added back](https://github.com/bloom-housing/ui-components/commit/fca0523227b5d40ae1d4fd475099532937bce757). The agreed upon resolution is to remove the Z-Index field.
Before: 
After:
1. On DAHLIA, go to `/listings/a0W0P00000GwGl3UAF` and open the inspector.
2. Turn on the mobile emulator
3. Open the slide-out menu by tapping the hamburger icon in the top right
4. The tag will be underneath the menu
On another website, open a listing that uses tags and follow steps 2 through 4.
- Read and …
=> fix: remove z-index

src/actions/Button.tsx
#126 
This PR adds an aria-expanded prop to the button component. This will allow us to make our show more / show less functionality more accessible.
This is an optional accessibility change. To test, check it out in a test environment and toggle the value of the role.
=> fix: add aria expanded attribute to button

src/forms/Field.tsx
This PR addresses Issue [#130](https://github.com/bloom-housing/ui-components/issues/130).
For the Field component, the aria-describedby is linked to the ErrorMessage id so that a screen reader can announce a potential error message. However, the ErrorMessage is conditionally rendered, and the aria-describedby needs to reference an existing element in the DOM.
This points the aria-describedby attribute to an empty element if there is no error, and the error message if an error is detected.
- Review the code itself from a style point of …
=> fix: error accessibility

__tests__/forms/PhoneField.test.tsx, src/forms/DOBField.tsx, src/forms/PhoneField.tsx, src/forms/PhoneMask.tsx, src/global/forms.scss, src/global/text.scss, src/helpers/MultiLineAddress.tsx, src/navigation/ProgressNav.scss, src/page_components/ApplicationTimeline.scss
[Doorway alignment issue
](https://github.com/metrotranscom/doorway/issues/364)
A handful of changes to support the updates to the common app in core. I left comments on most of the files to clarify.
Check out the ProgressNav component with the recent updates in [Storybook](https://deploy-preview-132--storybook-bloom-dev.netlify.app/?path=/story/navigation-progress-nav-%F0%9F%9A%A9--default).
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is …
=> refactor: update application styles

src/blocks/ImageCard.tsx
https://sfgovdt.jira.com/browse/DAH-1856
- On DAHLIA we need to dynamically translate alt text for the listing image(s)
- We use the `translate` class name to tell Google Translate to translate text contained in the element
- I could not find a graceful way to add this class name without editing the `ImageCard` component
- I added a new prop called `innerClassName` which is added to the `innerClasses` array
- Go to listings/a0W4U00000IgrACUAZ?react=true
- Inspect alt text for the image
- Switch to a different language
- Ensure alt text is translated
- Set this prop to a class name when using the `ImageCard` component
- Inspect and ensure that the passed class is applied to the `figure` element …
=> feat: add innerClassName prop to ImageCard component

src/icons/HeaderBadge.scss
#145 
Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context.
=> fix: correctly spell apply in HeaderBadge.scss

src/forms/Field.tsx, src/forms/Textarea.tsx
https://github.com/metrotranscom/doorway/issues/601
Removes the title attribute from form fields. We were using this incorrectly - looks like it is meant to be used to provide additional information or as a label for screen readers when adding an actual label isn't possible. It adds a tooltip on the form elements that we don't want.
=> fix: remove tooltip text

src/headers/SiteHeader.scss, src/headers/SiteHeader.stories.tsx, src/headers/SiteHeader.tsx
#151 
This change adds the following things to the menu:
- A 20px buffer zone around the menu dropdown to allow for a little bit more give when it comes to the mouseOut to close behavior
- Option to use a consumer provided iconElement instead of iconSrc
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes …
=> feat: improve menu flexibility

src/forms/Field.tsx
#153 
In order to support DAHLIA accounts work and have password show/hide functionality we need to add an optional prop to the Field component.
=> fix: Add optional post input content prop for Field

src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
#issue
https://sfgovdt.jira.com/browse/DAH-3015
Add a priority prop to override header priority
Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context.
No visible changes, consumer can override priority via priority prop
- Either explicitly ask a clarifying question, request changes, or approve the PR …
=> fix: add missing priority prop

src/page_components/listing/listing_sidebar/QuantityRowSection.stories.tsx, src/page_components/listing/listing_sidebar/QuantityRowSection.tsx
https://github.com/bloom-housing/bloom/issues/4858
A three digit waitlist size was wrapping onto multiple lines.
Check out the [new story](https://deploy-preview-171--storybook-bloom-dev.netlify.app/?path=/story/listing-sidebar-quantity-row-section--custom-description). This is not the most elegant fix, but didn't want to sink too much time into UIC.
=> fix: five digit waitlist size
